#build
FROM FROM node:14.19.3-alpine3.15 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

#production
FROM nginx:1.15

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]